### ISSUE TITLE
SSLHandshakeException with Glide

### ISSUE THREAD

**Issue by hocplyr98** [chrisbanes/tivi#111]
Glide won't load images from TMDB due to the SSLHandshakeException.

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by chrisbanes** [comment]
Weird. I've never seen this and I don't think this is an issue with this app or Glide.

Maybe you're hitting a badly configured TMDb edge server?

**Comment by chrisbanes** [comment]
Can you post the full exception please?

**Comment by hocplyr98** [comment]
Sorry I wasn't specific! Never received a crash, just a list of exception of Glide failing to load the images.

01-23 16:41:46.001 6141-6141/me.banes.chris.tivi W/Glide: Load failed for https://image.tmdb.org/t/p/w185/ihvG9dCEnVU3gmMUftTkRICNdJf.jpg with size [255x383]
                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                              Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
01-23 16:41:46.001 6141-6141/me.banes.chris.tivi I/Glide: Root cause (1 of 1)
                                                          javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                              at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
                                                              at com.android.okhttp.Connection.connectTls(Connection.java:235)
                                                              at com.android.okhttp.Connection.connectSocket(Connection.java:199)
                                                              at com.android.okhttp.Connection.connect(Connection.java:172)
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                              at com.google.firebase.perf.network.zze.connect(Unknown Source)
                                                              at com.google.firebase.perf.network.zzd.connect(Unknown Source)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at java.lang.Thread.run(Thread.java:761)
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
                                                           Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
                                                              at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
                                                              at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                              at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
                                                              at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
                                                              at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
                                                              at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                              at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
                                                              at com.android.okhttp.Connection.connectTls(Connection.java:235) 
                                                              at com.android.okhttp.Connection.connectSocket(Connection.java:199) 
                                                              at com.android.okhttp.Connection.connect(Connection.java:172) 
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130) 
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329) 
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126) 
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
                                                              at com.google.firebase.perf.network.zze.connect(Unknown Source) 
                                                              at com.google.firebase.perf.network.zzd.connect(Unknown Source) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                              at java.lang.Thread.run(Thread.java:761) 
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386) 
                                                           Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549) 
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508) 
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508) 
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401) 
                                                              at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375) 
                                                              at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304) 
                                                              at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94) 
                                                              at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88) 
                                                              at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178) 
                                                              at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596) 
                                                              at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                              at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357) 
                                                              at com.android.okhttp.Connection.connectTls(Connection.java:235) 
                                                              at com.android.okhttp.Connection.connectSocket(Connection.java:199) 
                                                              at com.android.okhttp.Connection.connect(Connection.java:172) 
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130) 
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329) 
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126) 
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
                                                              at com.google.firebase.perf.network.zze.connect(Unknown Source) 
                                                              at com.google.firebase.perf.network.zzd.connect(Unknown Source) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141) 
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60) 
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263) 
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                              at java.lang.Thread.run(Thread.java:761) 
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)

**Comment by hocplyr98** [comment]
It seems like it's a problem with the emulator. I hooked up a physical device and it works as expected. Closing the issue.
