### ISSUE TITLE
Building app from main and launching fails with IllegalStateException (Firebase)

### ISSUE THREAD

**Issue by christofferqa** [chrisbanes/tivi#1445]
Building from main (20513754df3f78d70135b8dd09d95f6933bee29a) and launching the app on a device fails with the below error.

Is this a bug in the app code, or must Firebase be configured locally somehow to successfully launch the app?

```
08-02 14:10:13.511 22947 22947 E AndroidRuntime: FATAL EXCEPTION: main
08-02 14:10:13.511 22947 22947 E AndroidRuntime: Process: app.tivi, PID: 22947
08-02 14:10:13.511 22947 22947 E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process app.tivi. Make sure to call FirebaseApp.initializeApp(Context) first.
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at RG.b(SourceFile:54)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at SG.a(SourceFile:1)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at tr.b(SourceFile:121)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at hu0.b(SourceFile:37)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at JS.b(SourceFile:102)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at pt.r0(SourceFile:127)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at DI.i(SourceFile:12)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at Sb.m(SourceFile:9)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at xy.run(SourceFile:114)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at Z4.x0(SourceFile:7)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at Y4.run(SourceFile:3)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-02 14:10:13.511 22947 22947 E AndroidRuntime: 	Suppressed: kx: [z90@e98714c, Ud@6359595, lJ0{Cancelling}@ea246aa, Z4@e1c129b]
08-02 14:10:13.516  2184 10169 W ActivityTaskManager:   Force finishing activity app.tivi/.home.MainActivity
```

**Comment by christofferqa** [comment]
Thanks for the quick turnaround!

**Comment by davidqphan** [comment]
Hi @chrisbanes I built the app from main, and faced a similar issue to this. Do I need to configure Firebase? See stack trace

```
2024-02-17 15:26:45.306  3252-3280  Compatibil...geReporter app.tivi.debug                       D  Compat change id reported: 247079863; UID 10141; state: ENABLED
2024-02-17 15:26:45.308  3252-3280  ImageLoade...CoilLogger app.tivi.debug                       I  onConnectivityChange: The device is online.
2024-02-17 15:26:45.320  3252-3280  AndroidRuntime          app.tivi.debug                       E  FATAL EXCEPTION: ConnectivityThread
                                                                                                    Process: app.tivi.debug, PID: 3252
                                                                                                    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process app.tivi.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                                                                    	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:213)
                                                                                                    	at co.touchlab.crashkios.crashlytics.CrashlyticsCallsActual.logMessage(CrashlyticsCallsActual.kt:7)
                                                                                                    	at co.touchlab.crashkios.crashlytics.CrashlyticsKotlin.logMessage(CrashlyticsKotlin.kt:9)
                                                                                                    	at app.tivi.util.CrashlyticsTree.log(TimberLogger.kt:94)
                                                                                                    	at timber.log.Timber$Tree.prepareLog(Timber.kt:168)
                                                                                                    	at timber.log.Timber$Tree.i(Timber.kt:71)
                                                                                                    	at timber.log.Timber$Forest.i(Timber.kt:312)
                                                                                                    	at app.tivi.util.TimberLogger.i(TimberLogger.kt:45)
                                                                                                    	at app.tivi.util.CompositeLogger.i(CompositeLogger.kt:26)
                                                                                                    	at app.tivi.common.imageloading.ImageLoaderKt$asCoilLogger$1.log(ImageLoader.kt:58)
                                                                                                    	at coil3.util.AndroidSystemCallbacks.onConnectivityChange(SystemCallbacks.kt:111)
                                                                                                    	at coil3.util.RealNetworkObserver.onConnectivityChange(NetworkObserver.kt:69)
                                                                                                    	at coil3.util.RealNetworkObserver.access$onConnectivityChange(NetworkObserver.kt:34)
                                                                                                    	at coil3.util.RealNetworkObserver$networkCallback$1.onAvailable(NetworkObserver.kt:42)
                                                                                                    	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3954)
                                                                                                    	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3936)
                                                                                                    	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:4263)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-17 15:26:45.358  3252-3280  Process                 app.tivi.debug                       I  Sending signal. PID: 3252 SIG: 9
---------------------------- PROCESS ENDED (3252) for package app.tivi.debug ----------------------------
```
