### ISSUE TITLE
The app crashes if the device/emulator does not have a network connection on first run

### ISSUE THREAD

**Issue by emmano** [chrisbanes/tivi#146]
First of, I want to thank you for this awesome repo.

I am trying to grasp error handling around coroutines (still new to coroutines in general), specially when making API calls. When I launched the app with no network connectivity for the first time the app crashes:

```
FATAL EXCEPTION: ForkJoinPool.commonPool-worker-2
                                                Process: me.banes.chris.tivi, PID: 11029
                                                java.lang.IllegalStateException: Unknown exception from fetchBodyWithRetry
                                                          at me.banes.chris.tivi.trakt.calls.PopularCall.networkCall(PopularCall.kt:99)
                                                          at me.banes.chris.tivi.trakt.calls.PopularCall$networkCall$1.doResume(Unknown Source:14)
                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                          at kotlinx.coroutines.experimental.ResumeModeKt.resumeMode(ResumeMode.kt:56)
                                                          at kotlinx.coroutines.experimental.DispatchedKt.dispatch(Dispatched.kt:193)
                                                          at kotlinx.coroutines.experimental.AbstractContinuation.onCompletionInternal$kotlinx_coroutines_core(AbstractContinuation.kt:86)
                                                          at kotlinx.coroutines.experimental.JobSupport.completeUpdateState$kotlinx_coroutines_core(Job.kt:704)
                                                          at kotlinx.coroutines.experimental.JobSupport.updateState$kotlinx_coroutines_core(Job.kt:655)
                                                          at kotlinx.coroutines.experimental.AbstractContinuation.resumeImpl(AbstractContinuation.kt:99)
                                                          at kotlinx.coroutines.experimental.CancellableContinuationImpl.resumeUndispatched(CancellableContinuation.kt:272)
                                                          at kotlinx.coroutines.experimental.rx2.SchedulerCoroutineDispatcher$scheduleResumeAfterDelay$disposable$1.run(RxScheduler.kt:44)
                                                          at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                          at java.lang.Thread.run(Thread.java:764)
```

When dealing with coroutines, is the correct approach to just use `try{}` `catch{}`? Also, this is more of a general question, coroutines are meant to be a "replacement" for Rx, right? Meaning, if you had something that returned `Flowable<T>`, `Maybe<T>`, `SIngle<T>`, `Observable<T>`, etc and you want to use coroutines, you can just deal with the underlying `T` ( as you did when you switched from Rx to coroutines)

**Comment by vipulasri** [comment]
Facing the same issue

**Comment by emmano** [comment]
You need to add API keys and client secrets for Trakt and TMDb. Look at the README.
