### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by mzgreen** [chrisbanes/tivi#25]
When I was reading the code I noticed that you are handling errors in RxJava streams using `doOnError` like here: https://github.com/chrisbanes/tivi/blob/7e020c15b477419ac16a0a266850952a58ee6770/app/src/main/java/me/banes/chris/tivi/util/PaginatedTraktViewModel.kt#L50

The problem is that `doOnError()` allows for side effects, but it passes the exception through downstream. So in this case I think that you'll get an `OnErrorNotImplementedException` when `loadNextPage()` emits an error.

**Comment by Bringoff** [comment]
Yep, just built and got such crash: 
```
3761-3791/me.banes.chris.tivi W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 403 
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onError(CompletableFromSingle.java:41)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:64)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
3761-3791/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
3761-3791/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
3761-3791/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3761-3791/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
3761-3791/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
3761-3791/me.banes.chris.tivi W/System.err: Caused by: retrofit2.HttpException: HTTP 403 
3761-3791/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.BodyObserver.onNext(RetrofitExtensions.kt:99)
3761-3791/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.BodyObserver.onNext(RetrofitExtensions.kt:87)
3761-3791/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.RetrofitCallObservable.subscribeActual(RetrofitExtensions.kt:49)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
3761-3791/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.BodyObservable.subscribeActual(RetrofitExtensions.kt:83)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10903)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.Single.subscribe(Single.java:2700)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
3761-3791/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
3761-3791/me.banes.chris.tivi W/System.err: 	... 5 more
```
