### ISSUE TITLE
Crash scrolling recyclerviews

### ISSUE THREAD

**Issue by nealsanche** [chrisbanes/tivi#35]
Decided to try out your app and try to learn some of the things you've been building here. The app crashes when scrolling a long list:

```10-13 11:57:33.856 4764-5094/me.banes.chris.tivi D/OkHttp: <-- 429 https://api.themoviedb.org/3/tv/69050?api_key=b6a1a71628cd5b44ab71457a30a9e516 (431ms, 95-byte body)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:86)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onError(FlowableElementAtMaybe.java:94)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.onError(MaybeConcatArray.java:100)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onError(MaybeFromSingle.java:82)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:   ComposedException 1 :
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err: 	java.lang.IllegalStateException: closed
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:393)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at okio.RealBufferedSource.readAll(RealBufferedSource.java:163)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at retrofit2.Utils.buffer(Utils.java:304)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:204)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.RetrofitCallObservable.subscribeActual(RetrofitExtensions.kt:47)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10910)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.BodyObservable.subscribeActual(RetrofitExtensions.kt:83)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10910)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Single.subscribe(Single.java:2779)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:   ComposedException 2 :
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err: 	java.lang.IllegalStateException: Cannot invoke setValue on a background thread
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.LiveData.assertMainThread(LiveData.java:404)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.LiveData.setValue(LiveData.java:289)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel.onError(EntryViewModel.kt:74)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel.access$onError(EntryViewModel.kt:30)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel$data$2$updateCall$1$1$1$1$2.invoke(EntryViewModel.kt:46)
10-13 11:57:33.856 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel$data$2$updateCall$1$1$1$1$2.invoke(EntryViewModel.kt:30)
10-13 11:57:33.857 4764-5072/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModelKt$sam$Consumer$c58a7660.accept(EntryViewModel.kt:0)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onError(FlowableElementAtMaybe.java:94)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.onError(MaybeConcatArray.java:100)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onError(MaybeFromSingle.java:82)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-13 11:57:33.858 4764-5072/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:86)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onError(FlowableElementAtMaybe.java:94)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.onError(MaybeConcatArray.java:100)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onError(MaybeFromSingle.java:82)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err:   ComposedException 1 :
10-13 11:57:33.858 4764-4803/me.banes.chris.tivi W/System.err: 	java.lang.IllegalStateException: closed
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:393)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at okio.RealBufferedSource.readAll(RealBufferedSource.java:163)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at retrofit2.Utils.buffer(Utils.java:304)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:204)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.RetrofitCallObservable.subscribeActual(RetrofitExtensions.kt:47)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10910)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.extensions.BodyObservable.subscribeActual(RetrofitExtensions.kt:83)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10910)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.Single.subscribe(Single.java:2779)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at java.lang.Thread.run(Thread.java:764)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:   ComposedException 2 :
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err: 	java.lang.IllegalStateException: Cannot invoke setValue on a background thread
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.LiveData.assertMainThread(LiveData.java:404)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.LiveData.setValue(LiveData.java:289)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel.onError(EntryViewModel.kt:74)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel.access$onError(EntryViewModel.kt:30)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel$data$2$updateCall$1$1$1$1$2.invoke(EntryViewModel.kt:46)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModel$data$2$updateCall$1$1$1$1$2.invoke(EntryViewModel.kt:30)
10-13 11:57:33.859 4764-4803/me.banes.chris.tivi W/System.err:     at me.banes.chris.tivi.util.EntryViewModelKt$sam$Consumer$c58a7660.accept(EntryViewModel.kt:0)
```

**Comment by nealsanche** [comment]
Quite the stack trace, hey?

**Comment by chrisbanes** [comment]
Woops, nice easy fix though.
