### ISSUE TITLE
java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by elvedinelvis** [chrisbanes/tivi#416]
App crashed when I tried following a show (not logged in).
I have all API-keys defined in my gradle.properties.

`2019-08-22 21:50:33.267 9467-9551/app.tivi.debug D/FollowedShowsRepository: addFollowedShow. Current entry: null
2019-08-22 21:50:33.294 9467-9551/app.tivi.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-12
    Process: app.tivi.debug, PID: 9467
    java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
        at io.fabric.sdk.android.Fabric.singleton(Fabric.java:301)
        at io.fabric.sdk.android.Fabric.getKit(Fabric.java:551)
        at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:191)
        at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:390)
        at com.crashlytics.android.Crashlytics.log(Crashlytics.java:221)
        at app.tivi.util.CrashlyticsTree.log(TiviLogger.kt:146)
        at timber.log.Timber$Tree.prepareLog(Timber.java:532)
        at timber.log.Timber$Tree.d(Timber.java:405)
        at timber.log.Timber$1.d(Timber.java:243)
        at timber.log.Timber.d(Timber.java:38)
        at app.tivi.util.TiviLogger.d(TiviLogger.kt:47)
        at app.tivi.data.repositories.followedshows.FollowedShowsRepository.addFollowedShow(FollowedShowsRepository.kt:68)
        at app.tivi.data.repositories.followedshows.FollowedShowsRepository$addFollowedShow$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)`

**Comment by chrisbanes** [comment]
Sounds like your `TIVI_FABRIC_API_KEY` isn't set correctly

**Comment by chrisbanes** [comment]
Sounds like your `TIVI_FABRIC_API_KEY` isn't set correctly
