### ISSUE TITLE
app.tivi.data.resultentities.FollowedShowEntryWithShow.getEntry()' on a null object reference

### ISSUE THREAD

**Issue by elvedinelvis** [chrisbanes/tivi#417]
`2019-08-22 21:59:38.127 9857-9911/app.tivi.debug E/DiscoverViewModel: Exception during observe
    java.lang.NullPointerException: Attempt to invoke virtual method 'app.tivi.data.entities.FollowedShowEntry app.tivi.data.resultentities.FollowedShowEntryWithShow.getEntry()' on a null object reference
        at app.tivi.domain.observers.ObserveNextShowEpisodeToWatch$createObservable$1.invokeSuspend(ObserveNextShowEpisodeToWatch.kt:39)
        at app.tivi.domain.observers.ObserveNextShowEpisodeToWatch$createObservable$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)`

**Comment by chrisbanes** [comment]
I think this is now fixed. I also haven't seen this in Crashlytics. Closing for now.
