### ISSUE TITLE
Unknown destination during deep link

### ISSUE THREAD

**Issue by PHELAT** [chrisbanes/tivi#571]
### Steps to reproduce:
- Click on MORE button in the discover page
- Rotate your device
- Click on the toolbar's back button

### Device specification:
Android Emulator with Android 7.1.1 (Google APIs) Image

### Stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.tivi.debug/app.tivi.home.HomeActivity}: java.lang.IllegalStateException: unknown destination during deep link: app.tivi.debug:id/navigation_discover
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalStateException: unknown destination during deep link: app.tivi.debug:id/navigation_discover
        at androidx.navigation.NavController.handleDeepLink(NavController.java:660)
        at androidx.navigation.NavController.onGraphCreated(NavController.java:573)
        at androidx.navigation.NavController.setGraph(NavController.java:534)
        at androidx.navigation.NavController.setGraph(NavController.java:499)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:246)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at app.tivi.extensions.MultipleBackStackNavigationExtensionsKt.obtainNavHostFragment(MultipleBackStackNavigationExtensions.kt:235)
        at app.tivi.extensions.MultipleBackStackNavigationExtensionsKt.setupWithNavController(MultipleBackStackNavigationExtensions.kt:55)
        at app.tivi.home.HomeActivity.setupBottomNavigationBar(HomeActivity.kt:88)
        at app.tivi.home.HomeActivity.onCreate(HomeActivity.kt:53)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
```

**Comment by chrisbanes** [comment]
This was fixed in #706
