### ISSUE TITLE
App crashes on startup with Firebase error

### ISSUE THREAD

**Issue by dturner** [chrisbanes/tivi#847]
When I attempt to run the app from Android Studio (tested on Pixel 3A emulator and Pixel 5 device) the app crashes on startup. The following messages are observed in logcat: 

```
2021-08-12 23:24:52.725 12896-12896/app.tivi.debug W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
```

then later

```
2021-08-12 23:24:52.897 12896-12896/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.tivi.debug, PID: 12896
    java.lang.RuntimeException: Unable to create application app.tivi.TiviApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process app.tivi.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process app.tivi.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:175)
        at app.tivi.inject.AppModule.provideFirebaseCrashlytics(AppModule.kt:116)
        at app.tivi.inject.AppModule_ProvideFirebaseCrashlyticsFactory.provideFirebaseCrashlytics(AppModule_ProvideFirebaseCrashlyticsFactory.java:25)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC$SwitchingProvider.get(DaggerTiviApplication_HiltComponents_SingletonC.java:2065)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.tiviLogger(DaggerTiviApplication_HiltComponents_SingletonC.java:498)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.timberInitializer(DaggerTiviApplication_HiltComponents_SingletonC.java:502)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.setOfAppInitializer(DaggerTiviApplication_HiltComponents_SingletonC.java:570)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.appInitializers(DaggerTiviApplication_HiltComponents_SingletonC.java:574)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.injectTiviApplication2(DaggerTiviApplication_HiltComponents_SingletonC.java:1067)
        at app.tivi.DaggerTiviApplication_HiltComponents_SingletonC.injectTiviApplication(DaggerTiviApplication_HiltComponents_SingletonC.java:1053)
        at app.tivi.Hilt_TiviApplication.onCreate(Hilt_TiviApplication.java:41)
        at app.tivi.TiviApplication.onCreate(TiviApplication.kt:32)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by hsicen** [comment]
same with me.

**Comment by ahmedshaban1** [comment]
same with me.

**Comment by ahmedshaban1** [comment]
I have the same issue
