### ISSUE TITLE
Crash: FTS expression tree is too large (maximum depth 12)

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/tivi#885]
From Crashlytics:

```
Fatal Exception: android.database.sqlite.SQLiteException: FTS expression tree is too large (maximum depth 12) (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:943)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
       at androidx.room.util.DBUtil.query(DBUtil.java:89)
       at app.tivi.data.daos.ShowFtsDao_Impl$1.call(ShowFtsDao_Impl.java:67)
       at app.tivi.data.daos.ShowFtsDao_Impl$1.call$bridge(ShowFtsDao_Impl.java:4)
       at app.tivi.data.daos.ShowFtsDao_Impl$1.call(ShowFtsDao_Impl.java:62)
       at app.tivi.data.daos.EpisodeWatchEntryDao_Impl$24.call$bridge(EpisodeWatchEntryDao_Impl.java:28)
       at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:88)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
       at androidx.browser.customtabs.CustomTabsClient$2$3.run$bridge(CustomTabsClient.java:354)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by chrisbanes** [comment]
Closing as we no longer use FTS
