### ISSUE TITLE
Bug SuspendingWorkInteractor without catch

### ISSUE THREAD

**Issue by janderadutra** [chrisbanes/tivi#902]
abstract class SuspendingWorkInteractor<P : Any, T> : SubjectInteractor<P, T>() {
    override fun createObservable(params: P): Flow<T> = flow {
        emit(doWork(params))
    } **_**.catch { }**_** 
crash the app every time it searches for movies

**Comment by chrisbanes** [comment]
Please post the full stack trace.

**Comment by janderadutra** [comment]
retrofit2.HttpException: HTTP 500 Internal Server Error
        at app.tivi.extensions.RetrofitExtensionsKt.bodyOrThrow(RetrofitExtensions.kt:8)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
